import type { NavMenuItem } from "lib/functions/nav-menu-item.model";

export interface NavItemConfig {
    about: NavMenuItem
    announcements: NavMenuItem
    articles: NavMenuItem
    benefits: NavMenuItem
    bfsi: NavMenuItem
    bookADemo: NavMenuItem
    customer: NavMenuItem
    careerGrowth: NavMenuItem
    careers: NavMenuItem
    challenges: NavMenuItem
    challengesApp: NavMenuItem
    communications: NavMenuItem
    talent: NavMenuItem
    compete: NavMenuItem
    connect: NavMenuItem
    dataAdvisory: NavMenuItem
    dataExploration: NavMenuItem
    dataScience: NavMenuItem
    demo: NavMenuItem
    design: NavMenuItem
    development: NavMenuItem
    devCenter: NavMenuItem
    discord: NavMenuItem
    discordApp: NavMenuItem
    earn: NavMenuItem
    energyUtilities: NavMenuItem
    events: NavMenuItem
    expertise: NavMenuItem
    faq: NavMenuItem
    findMeData: NavMenuItem
    forums: NavMenuItem
    fullService: NavMenuItem
    gettingPaid: NavMenuItem
    gigs: NavMenuItem
    gigsApp: NavMenuItem
    healthCare: NavMenuItem
    healthPharma: NavMenuItem
    industries: NavMenuItem
    learn: NavMenuItem
    marathonMatches: NavMenuItem
    marathonMatchesApp: NavMenuItem
    media: NavMenuItem
    payments: NavMenuItem
    partners: NavMenuItem
    practice: NavMenuItem
    privacyPolicy: NavMenuItem
    products: NavMenuItem
    publicSector: NavMenuItem
    qa: NavMenuItem
    rapidDevMatches: NavMenuItem
    rapidDevMatchesApp: NavMenuItem
    retail: NavMenuItem
    review: NavMenuItem
    security: NavMenuItem
    selfService: NavMenuItem
    selfServiceApp: NavMenuItem
    singleRoundMatches: NavMenuItem
    singleRoundMatchesApp: NavMenuItem
    statistics: NavMenuItem
    successStories: NavMenuItem
    support: NavMenuItem
    talkToAnExpert: NavMenuItem
    technology: NavMenuItem
    theCommunity: NavMenuItem
    timeline: NavMenuItem
    topcoderAcademy: NavMenuItem
    topcoderAcademyApp: NavMenuItem
    topcoderOpen: NavMenuItem
    topCrowd: NavMenuItem
    websiteDesign: NavMenuItem
    whyTopcoder: NavMenuItem
}
