export interface NavMenuItem {
  children: NavMenuItem[]
  description: string
  host: string
  label: string
  path: string
  type?: 'cta'

  // props auto generated by parsing and merging
  // the above and parent props
  fullPath: string
  absUrl: string
}
