on: # event list
  push: # on a pull request to each of these branches
    branches:
      - master
  
env: # environment variables (available in any part of the action)
  NODE_VERSION: 16

jobs: # list of things to do
  update-version-patch:
    name: Update Version Patch # job name (unique id)
    runs-on: ubuntu-latest # on which machine to run
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Increment Version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version patch
          git push
